/*
  Warnings:

  - You are about to drop the `AdvancedMetrics` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `GameStat` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Play` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Player` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `PlayerStats` table. If the table is not empty, all the data it contains will be lost.
  - A unique constraint covering the columns `[otc_id,gsis_id]` on the table `contracts` will be added. If there are existing duplicate values, this will fail.

*/
-- DropForeignKey
ALTER TABLE "AdvancedMetrics" DROP CONSTRAINT "AdvancedMetrics_playerId_fkey";

-- DropForeignKey
ALTER TABLE "GameStat" DROP CONSTRAINT "GameStat_playerId_fkey";

-- DropForeignKey
ALTER TABLE "PlayerStats" DROP CONSTRAINT "PlayerStats_playerId_fkey";

-- DropIndex
DROP INDEX "contracts_gsis_id_idx";

-- DropIndex
DROP INDEX "contracts_year_signed_idx";

-- AlterTable
ALTER TABLE "contracts" ADD COLUMN     "apy" DOUBLE PRECISION,
ADD COLUMN     "college" TEXT,
ADD COLUMN     "cols" TEXT,
ADD COLUMN     "date_of_birth" TEXT,
ADD COLUMN     "draft_overall" BIGINT,
ADD COLUMN     "draft_round" BIGINT,
ADD COLUMN     "draft_team" TEXT,
ADD COLUMN     "draft_year" BIGINT,
ADD COLUMN     "guaranteed" DOUBLE PRECISION,
ADD COLUMN     "height" TEXT,
ADD COLUMN     "inflated_apy" DOUBLE PRECISION,
ADD COLUMN     "inflated_guaranteed" DOUBLE PRECISION,
ADD COLUMN     "inflated_value" DOUBLE PRECISION,
ADD COLUMN     "is_active" BOOLEAN,
ADD COLUMN     "otc_id" TEXT,
ADD COLUMN     "player" TEXT,
ADD COLUMN     "player_page" TEXT,
ADD COLUMN     "position" TEXT,
ADD COLUMN     "team" TEXT,
ADD COLUMN     "value" DOUBLE PRECISION,
ADD COLUMN     "weight" TEXT,
ADD COLUMN     "years" BIGINT,
ALTER COLUMN "year_signed" SET DATA TYPE BIGINT;

-- DropTable
DROP TABLE "AdvancedMetrics";

-- DropTable
DROP TABLE "GameStat";

-- DropTable
DROP TABLE "Play";

-- DropTable
DROP TABLE "Player";

-- DropTable
DROP TABLE "PlayerStats";

-- CreateTable
CREATE TABLE "combine" (
    "season" BIGINT,
    "draft_year" DOUBLE PRECISION,
    "draft_team" TEXT,
    "draft_round" DOUBLE PRECISION,
    "draft_ovr" DOUBLE PRECISION,
    "pfr_id" TEXT,
    "cfb_id" TEXT,
    "player_name" TEXT,
    "pos" TEXT,
    "school" TEXT,
    "ht" TEXT,
    "wt" DOUBLE PRECISION,
    "forty" DOUBLE PRECISION,
    "bench" DOUBLE PRECISION,
    "vertical" DOUBLE PRECISION,
    "broad_jump" DOUBLE PRECISION,
    "cone" DOUBLE PRECISION,
    "shuttle" DOUBLE PRECISION,
    "id" SERIAL NOT NULL,

    CONSTRAINT "combine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "depth_charts" (
    "dt" TEXT,
    "team" TEXT,
    "player_name" TEXT,
    "espn_id" TEXT,
    "gsis_id" TEXT,
    "pos_grp_id" TEXT,
    "pos_grp" TEXT,
    "pos_id" TEXT,
    "pos_name" TEXT,
    "pos_abb" TEXT,
    "pos_slot" BIGINT,
    "pos_rank" BIGINT,
    "season" BIGINT,
    "club_code" TEXT,
    "week" BIGINT,
    "game_type" TEXT,
    "depth_team" TEXT,
    "last_name" TEXT,
    "first_name" TEXT,
    "football_name" TEXT,
    "formation" TEXT,
    "jersey_number" TEXT,
    "position" TEXT,
    "elias_id" TEXT,
    "depth_position" TEXT,
    "full_name" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "depth_charts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "draft_picks" (
    "season" BIGINT,
    "round" BIGINT,
    "pick" BIGINT,
    "team" TEXT,
    "gsis_id" TEXT,
    "pfr_player_id" TEXT,
    "cfb_player_id" TEXT,
    "pfr_player_name" TEXT,
    "hof" BOOLEAN,
    "position" TEXT,
    "category" TEXT,
    "side" TEXT,
    "college" TEXT,
    "age" BIGINT,
    "to" BIGINT,
    "allpro" BIGINT,
    "probowls" BIGINT,
    "seasons_started" BIGINT,
    "w_av" BIGINT,
    "car_av" BOOLEAN,
    "dr_av" BIGINT,
    "games" BIGINT,
    "pass_completions" BIGINT,
    "pass_attempts" BIGINT,
    "pass_yards" BIGINT,
    "pass_tds" BIGINT,
    "pass_ints" BIGINT,
    "rush_atts" BIGINT,
    "rush_yards" BIGINT,
    "rush_tds" BIGINT,
    "receptions" BIGINT,
    "rec_yards" BIGINT,
    "rec_tds" BIGINT,
    "def_solo_tackles" BIGINT,
    "def_ints" BIGINT,
    "def_sacks" DOUBLE PRECISION,
    "id" SERIAL NOT NULL,

    CONSTRAINT "draft_picks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ff_opportunity" (
    "season" TEXT,
    "posteam" TEXT,
    "week" DOUBLE PRECISION,
    "game_id" TEXT,
    "player_id" TEXT,
    "full_name" TEXT,
    "position" TEXT,
    "pass_attempt" DOUBLE PRECISION,
    "rec_attempt" DOUBLE PRECISION,
    "rush_attempt" DOUBLE PRECISION,
    "pass_air_yards" DOUBLE PRECISION,
    "rec_air_yards" DOUBLE PRECISION,
    "pass_completions" DOUBLE PRECISION,
    "receptions" DOUBLE PRECISION,
    "pass_completions_exp" DOUBLE PRECISION,
    "receptions_exp" DOUBLE PRECISION,
    "pass_yards_gained" DOUBLE PRECISION,
    "rec_yards_gained" DOUBLE PRECISION,
    "rush_yards_gained" DOUBLE PRECISION,
    "pass_yards_gained_exp" DOUBLE PRECISION,
    "rec_yards_gained_exp" DOUBLE PRECISION,
    "rush_yards_gained_exp" DOUBLE PRECISION,
    "pass_touchdown" DOUBLE PRECISION,
    "rec_touchdown" DOUBLE PRECISION,
    "rush_touchdown" DOUBLE PRECISION,
    "pass_touchdown_exp" DOUBLE PRECISION,
    "rec_touchdown_exp" DOUBLE PRECISION,
    "rush_touchdown_exp" DOUBLE PRECISION,
    "pass_two_point_conv" DOUBLE PRECISION,
    "rec_two_point_conv" DOUBLE PRECISION,
    "rush_two_point_conv" DOUBLE PRECISION,
    "pass_two_point_conv_exp" DOUBLE PRECISION,
    "rec_two_point_conv_exp" DOUBLE PRECISION,
    "rush_two_point_conv_exp" DOUBLE PRECISION,
    "pass_first_down" DOUBLE PRECISION,
    "rec_first_down" DOUBLE PRECISION,
    "rush_first_down" DOUBLE PRECISION,
    "pass_first_down_exp" DOUBLE PRECISION,
    "rec_first_down_exp" DOUBLE PRECISION,
    "rush_first_down_exp" DOUBLE PRECISION,
    "pass_interception" DOUBLE PRECISION,
    "rec_interception" DOUBLE PRECISION,
    "pass_interception_exp" DOUBLE PRECISION,
    "rec_interception_exp" DOUBLE PRECISION,
    "rec_fumble_lost" DOUBLE PRECISION,
    "rush_fumble_lost" DOUBLE PRECISION,
    "pass_fantasy_points_exp" DOUBLE PRECISION,
    "rec_fantasy_points_exp" DOUBLE PRECISION,
    "rush_fantasy_points_exp" DOUBLE PRECISION,
    "pass_fantasy_points" DOUBLE PRECISION,
    "rec_fantasy_points" DOUBLE PRECISION,
    "rush_fantasy_points" DOUBLE PRECISION,
    "total_yards_gained" DOUBLE PRECISION,
    "total_yards_gained_exp" DOUBLE PRECISION,
    "total_touchdown" DOUBLE PRECISION,
    "total_touchdown_exp" DOUBLE PRECISION,
    "total_first_down" DOUBLE PRECISION,
    "total_first_down_exp" DOUBLE PRECISION,
    "total_fantasy_points" DOUBLE PRECISION,
    "total_fantasy_points_exp" DOUBLE PRECISION,
    "pass_completions_diff" DOUBLE PRECISION,
    "receptions_diff" DOUBLE PRECISION,
    "pass_yards_gained_diff" DOUBLE PRECISION,
    "rec_yards_gained_diff" DOUBLE PRECISION,
    "rush_yards_gained_diff" DOUBLE PRECISION,
    "pass_touchdown_diff" DOUBLE PRECISION,
    "rec_touchdown_diff" DOUBLE PRECISION,
    "rush_touchdown_diff" DOUBLE PRECISION,
    "pass_two_point_conv_diff" DOUBLE PRECISION,
    "rec_two_point_conv_diff" DOUBLE PRECISION,
    "rush_two_point_conv_diff" DOUBLE PRECISION,
    "pass_first_down_diff" DOUBLE PRECISION,
    "rec_first_down_diff" DOUBLE PRECISION,
    "rush_first_down_diff" DOUBLE PRECISION,
    "pass_interception_diff" DOUBLE PRECISION,
    "rec_interception_diff" DOUBLE PRECISION,
    "pass_fantasy_points_diff" DOUBLE PRECISION,
    "rec_fantasy_points_diff" DOUBLE PRECISION,
    "rush_fantasy_points_diff" DOUBLE PRECISION,
    "total_yards_gained_diff" DOUBLE PRECISION,
    "total_touchdown_diff" DOUBLE PRECISION,
    "total_first_down_diff" DOUBLE PRECISION,
    "total_fantasy_points_diff" DOUBLE PRECISION,
    "pass_attempt_team" DOUBLE PRECISION,
    "rec_attempt_team" DOUBLE PRECISION,
    "rush_attempt_team" DOUBLE PRECISION,
    "pass_air_yards_team" DOUBLE PRECISION,
    "rec_air_yards_team" DOUBLE PRECISION,
    "pass_completions_team" DOUBLE PRECISION,
    "receptions_team" DOUBLE PRECISION,
    "pass_completions_exp_team" DOUBLE PRECISION,
    "receptions_exp_team" DOUBLE PRECISION,
    "pass_yards_gained_team" DOUBLE PRECISION,
    "rec_yards_gained_team" DOUBLE PRECISION,
    "rush_yards_gained_team" DOUBLE PRECISION,
    "pass_yards_gained_exp_team" DOUBLE PRECISION,
    "rec_yards_gained_exp_team" DOUBLE PRECISION,
    "rush_yards_gained_exp_team" DOUBLE PRECISION,
    "pass_touchdown_team" DOUBLE PRECISION,
    "rec_touchdown_team" DOUBLE PRECISION,
    "rush_touchdown_team" DOUBLE PRECISION,
    "pass_touchdown_exp_team" DOUBLE PRECISION,
    "rec_touchdown_exp_team" DOUBLE PRECISION,
    "rush_touchdown_exp_team" DOUBLE PRECISION,
    "pass_two_point_conv_team" DOUBLE PRECISION,
    "rec_two_point_conv_team" DOUBLE PRECISION,
    "rush_two_point_conv_team" DOUBLE PRECISION,
    "pass_two_point_conv_exp_team" DOUBLE PRECISION,
    "rec_two_point_conv_exp_team" DOUBLE PRECISION,
    "rush_two_point_conv_exp_team" DOUBLE PRECISION,
    "pass_first_down_team" DOUBLE PRECISION,
    "rec_first_down_team" DOUBLE PRECISION,
    "rush_first_down_team" DOUBLE PRECISION,
    "pass_first_down_exp_team" DOUBLE PRECISION,
    "rec_first_down_exp_team" DOUBLE PRECISION,
    "rush_first_down_exp_team" DOUBLE PRECISION,
    "pass_interception_team" DOUBLE PRECISION,
    "rec_interception_team" DOUBLE PRECISION,
    "pass_interception_exp_team" DOUBLE PRECISION,
    "rec_interception_exp_team" DOUBLE PRECISION,
    "rec_fumble_lost_team" DOUBLE PRECISION,
    "rush_fumble_lost_team" DOUBLE PRECISION,
    "pass_fantasy_points_exp_team" DOUBLE PRECISION,
    "rec_fantasy_points_exp_team" DOUBLE PRECISION,
    "rush_fantasy_points_exp_team" DOUBLE PRECISION,
    "pass_fantasy_points_team" DOUBLE PRECISION,
    "rec_fantasy_points_team" DOUBLE PRECISION,
    "rush_fantasy_points_team" DOUBLE PRECISION,
    "pass_completions_diff_team" DOUBLE PRECISION,
    "receptions_diff_team" DOUBLE PRECISION,
    "pass_yards_gained_diff_team" DOUBLE PRECISION,
    "rec_yards_gained_diff_team" DOUBLE PRECISION,
    "rush_yards_gained_diff_team" DOUBLE PRECISION,
    "pass_touchdown_diff_team" DOUBLE PRECISION,
    "rec_touchdown_diff_team" DOUBLE PRECISION,
    "rush_touchdown_diff_team" DOUBLE PRECISION,
    "pass_two_point_conv_diff_team" DOUBLE PRECISION,
    "rec_two_point_conv_diff_team" DOUBLE PRECISION,
    "rush_two_point_conv_diff_team" DOUBLE PRECISION,
    "pass_first_down_diff_team" DOUBLE PRECISION,
    "rec_first_down_diff_team" DOUBLE PRECISION,
    "rush_first_down_diff_team" DOUBLE PRECISION,
    "pass_interception_diff_team" DOUBLE PRECISION,
    "rec_interception_diff_team" DOUBLE PRECISION,
    "pass_fantasy_points_diff_team" DOUBLE PRECISION,
    "rec_fantasy_points_diff_team" DOUBLE PRECISION,
    "rush_fantasy_points_diff_team" DOUBLE PRECISION,
    "total_yards_gained_team" DOUBLE PRECISION,
    "total_yards_gained_exp_team" DOUBLE PRECISION,
    "total_yards_gained_diff_team" DOUBLE PRECISION,
    "total_touchdown_team" DOUBLE PRECISION,
    "total_touchdown_exp_team" DOUBLE PRECISION,
    "total_touchdown_diff_team" DOUBLE PRECISION,
    "total_first_down_team" DOUBLE PRECISION,
    "total_first_down_exp_team" DOUBLE PRECISION,
    "total_first_down_diff_team" DOUBLE PRECISION,
    "total_fantasy_points_team" DOUBLE PRECISION,
    "total_fantasy_points_exp_team" DOUBLE PRECISION,
    "total_fantasy_points_diff_team" DOUBLE PRECISION,
    "id" SERIAL NOT NULL,

    CONSTRAINT "ff_opportunity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ff_playerids" (
    "mfl_id" BIGINT,
    "sportradar_id" TEXT,
    "fantasypros_id" BIGINT,
    "gsis_id" TEXT,
    "pff_id" BIGINT,
    "sleeper_id" BIGINT,
    "nfl_id" BIGINT,
    "espn_id" BIGINT,
    "yahoo_id" TEXT,
    "fleaflicker_id" TEXT,
    "cbs_id" BIGINT,
    "pfr_id" TEXT,
    "cfbref_id" TEXT,
    "rotowire_id" BIGINT,
    "rotoworld_id" TEXT,
    "ktc_id" BIGINT,
    "stats_id" BIGINT,
    "stats_global_id" BIGINT,
    "fantasy_data_id" BIGINT,
    "swish_id" TEXT,
    "name" TEXT,
    "merge_name" TEXT,
    "position" TEXT,
    "team" TEXT,
    "birthdate" TEXT,
    "age" DOUBLE PRECISION,
    "draft_year" BIGINT,
    "draft_round" BIGINT,
    "draft_pick" BIGINT,
    "draft_ovr" BIGINT,
    "twitter_username" TEXT,
    "height" BIGINT,
    "weight" BIGINT,
    "college" TEXT,
    "db_season" BIGINT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "ff_playerids_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ff_rankings" (
    "fp_page" TEXT NOT NULL,
    "page_type" TEXT,
    "ecr_type" TEXT,
    "player" TEXT,
    "id" BIGINT NOT NULL,
    "pos" TEXT,
    "team" TEXT,
    "ecr" DOUBLE PRECISION,
    "sd" DOUBLE PRECISION,
    "best" BIGINT,
    "worst" BIGINT,
    "sportsdata_id" TEXT,
    "player_filename" TEXT,
    "yahoo_id" TEXT,
    "cbs_id" TEXT,
    "player_owned_avg" DOUBLE PRECISION,
    "player_owned_espn" TEXT,
    "player_owned_yahoo" TEXT,
    "player_image_url" TEXT,
    "player_square_image_url" TEXT,
    "rank_delta" TEXT,
    "bye" BIGINT,
    "mergename" TEXT,
    "scrape_date" TEXT NOT NULL,
    "tm" TEXT,

    CONSTRAINT "ff_rankings_pkey" PRIMARY KEY ("fp_page","id","scrape_date")
);

-- CreateTable
CREATE TABLE "ftn_charting" (
    "ftn_game_id" BIGINT,
    "nflverse_game_id" TEXT,
    "season" BIGINT,
    "week" BIGINT,
    "ftn_play_id" BIGINT,
    "nflverse_play_id" BIGINT,
    "starting_hash" TEXT,
    "qb_location" TEXT,
    "n_offense_backfield" BIGINT,
    "n_defense_box" BIGINT,
    "is_no_huddle" BOOLEAN,
    "is_motion" BOOLEAN,
    "is_play_action" BOOLEAN,
    "is_screen_pass" BOOLEAN,
    "is_rpo" BOOLEAN,
    "is_trick_play" BOOLEAN,
    "is_qb_out_of_pocket" BOOLEAN,
    "is_interception_worthy" BOOLEAN,
    "is_throw_away" BOOLEAN,
    "read_thrown" TEXT,
    "is_catchable_ball" BOOLEAN,
    "is_contested_ball" BOOLEAN,
    "is_created_reception" BOOLEAN,
    "is_drop" BOOLEAN,
    "is_qb_sneak" BOOLEAN,
    "n_blitzers" BIGINT,
    "n_pass_rushers" BIGINT,
    "is_qb_fault_sack" BOOLEAN,
    "date_pulled" TIMESTAMP(6),
    "id" SERIAL NOT NULL,

    CONSTRAINT "ftn_charting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "nextgen_stats" (
    "season" BIGINT,
    "season_type" TEXT,
    "week" BIGINT,
    "player_display_name" TEXT,
    "player_position" TEXT,
    "team_abbr" TEXT,
    "avg_time_to_throw" DOUBLE PRECISION,
    "avg_completed_air_yards" DOUBLE PRECISION,
    "avg_intended_air_yards" DOUBLE PRECISION,
    "avg_air_yards_differential" DOUBLE PRECISION,
    "aggressiveness" DOUBLE PRECISION,
    "max_completed_air_distance" DOUBLE PRECISION,
    "avg_air_yards_to_sticks" DOUBLE PRECISION,
    "attempts" BIGINT,
    "pass_yards" BIGINT,
    "pass_touchdowns" BIGINT,
    "interceptions" BIGINT,
    "passer_rating" DOUBLE PRECISION,
    "completions" BIGINT,
    "completion_percentage" DOUBLE PRECISION,
    "expected_completion_percentage" DOUBLE PRECISION,
    "completion_percentage_above_expectation" DOUBLE PRECISION,
    "avg_air_distance" DOUBLE PRECISION,
    "max_air_distance" DOUBLE PRECISION,
    "player_gsis_id" TEXT,
    "player_first_name" TEXT,
    "player_last_name" TEXT,
    "player_jersey_number" BIGINT,
    "player_short_name" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "nextgen_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "officials" (
    "game_id" TEXT,
    "game_key" TEXT,
    "official_name" TEXT,
    "position" TEXT,
    "jersey_number" BIGINT,
    "official_id" TEXT,
    "season" BIGINT,
    "season_type" TEXT,
    "week" BIGINT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "officials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "participation" (
    "nflverse_game_id" TEXT,
    "old_game_id" TEXT,
    "play_id" DOUBLE PRECISION,
    "possession_team" TEXT,
    "offense_formation" TEXT,
    "offense_personnel" TEXT,
    "defenders_in_box" BIGINT,
    "defense_personnel" TEXT,
    "number_of_pass_rushers" BIGINT,
    "players_on_play" TEXT,
    "offense_players" TEXT,
    "defense_players" TEXT,
    "n_offense" BIGINT,
    "n_defense" BIGINT,
    "ngs_air_yards" DOUBLE PRECISION,
    "time_to_throw" DOUBLE PRECISION,
    "was_pressure" BOOLEAN,
    "route" TEXT,
    "defense_man_zone_type" TEXT,
    "defense_coverage_type" TEXT,
    "offense_names" TEXT,
    "defense_names" TEXT,
    "offense_positions" TEXT,
    "defense_positions" TEXT,
    "offense_numbers" TEXT,
    "defense_numbers" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "participation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pbp" (
    "play_id" DOUBLE PRECISION NOT NULL,
    "game_id" TEXT NOT NULL,
    "old_game_id" TEXT,
    "home_team" TEXT,
    "away_team" TEXT,
    "season_type" TEXT,
    "week" BIGINT,
    "posteam" TEXT,
    "posteam_type" TEXT,
    "defteam" TEXT,
    "side_of_field" TEXT,
    "yardline_100" DOUBLE PRECISION,
    "game_date" TEXT,
    "quarter_seconds_remaining" DOUBLE PRECISION,
    "half_seconds_remaining" DOUBLE PRECISION,
    "game_seconds_remaining" DOUBLE PRECISION,
    "game_half" TEXT,
    "quarter_end" DOUBLE PRECISION,
    "drive" DOUBLE PRECISION,
    "sp" DOUBLE PRECISION,
    "qtr" DOUBLE PRECISION,
    "down" DOUBLE PRECISION,
    "goal_to_go" BIGINT,
    "time" TEXT,
    "yrdln" TEXT,
    "ydstogo" DOUBLE PRECISION,
    "ydsnet" DOUBLE PRECISION,
    "desc" TEXT,
    "play_type" TEXT,
    "yards_gained" DOUBLE PRECISION,
    "shotgun" DOUBLE PRECISION,
    "no_huddle" DOUBLE PRECISION,
    "qb_dropback" DOUBLE PRECISION,
    "qb_kneel" DOUBLE PRECISION,
    "qb_spike" DOUBLE PRECISION,
    "qb_scramble" DOUBLE PRECISION,
    "pass_length" TEXT,
    "pass_location" TEXT,
    "air_yards" DOUBLE PRECISION,
    "yards_after_catch" DOUBLE PRECISION,
    "run_location" TEXT,
    "run_gap" TEXT,
    "field_goal_result" TEXT,
    "kick_distance" DOUBLE PRECISION,
    "extra_point_result" TEXT,
    "two_point_conv_result" TEXT,
    "home_timeouts_remaining" DOUBLE PRECISION,
    "away_timeouts_remaining" DOUBLE PRECISION,
    "timeout" DOUBLE PRECISION,
    "timeout_team" TEXT,
    "td_team" TEXT,
    "td_player_name" TEXT,
    "td_player_id" TEXT,
    "posteam_timeouts_remaining" DOUBLE PRECISION,
    "defteam_timeouts_remaining" DOUBLE PRECISION,
    "total_home_score" DOUBLE PRECISION,
    "total_away_score" DOUBLE PRECISION,
    "posteam_score" DOUBLE PRECISION,
    "defteam_score" DOUBLE PRECISION,
    "score_differential" DOUBLE PRECISION,
    "posteam_score_post" DOUBLE PRECISION,
    "defteam_score_post" DOUBLE PRECISION,
    "score_differential_post" DOUBLE PRECISION,
    "no_score_prob" DOUBLE PRECISION,
    "opp_fg_prob" DOUBLE PRECISION,
    "opp_safety_prob" DOUBLE PRECISION,
    "opp_td_prob" DOUBLE PRECISION,
    "fg_prob" DOUBLE PRECISION,
    "safety_prob" DOUBLE PRECISION,
    "td_prob" DOUBLE PRECISION,
    "extra_point_prob" DOUBLE PRECISION,
    "two_point_conversion_prob" DOUBLE PRECISION,
    "ep" DOUBLE PRECISION,
    "epa" DOUBLE PRECISION,
    "total_home_epa" DOUBLE PRECISION,
    "total_away_epa" DOUBLE PRECISION,
    "total_home_rush_epa" DOUBLE PRECISION,
    "total_away_rush_epa" DOUBLE PRECISION,
    "total_home_pass_epa" DOUBLE PRECISION,
    "total_away_pass_epa" DOUBLE PRECISION,
    "air_epa" DOUBLE PRECISION,
    "yac_epa" DOUBLE PRECISION,
    "comp_air_epa" DOUBLE PRECISION,
    "comp_yac_epa" DOUBLE PRECISION,
    "total_home_comp_air_epa" DOUBLE PRECISION,
    "total_away_comp_air_epa" DOUBLE PRECISION,
    "total_home_comp_yac_epa" DOUBLE PRECISION,
    "total_away_comp_yac_epa" DOUBLE PRECISION,
    "total_home_raw_air_epa" DOUBLE PRECISION,
    "total_away_raw_air_epa" DOUBLE PRECISION,
    "total_home_raw_yac_epa" DOUBLE PRECISION,
    "total_away_raw_yac_epa" DOUBLE PRECISION,
    "wp" DOUBLE PRECISION,
    "def_wp" DOUBLE PRECISION,
    "home_wp" DOUBLE PRECISION,
    "away_wp" DOUBLE PRECISION,
    "wpa" DOUBLE PRECISION,
    "vegas_wpa" DOUBLE PRECISION,
    "vegas_home_wpa" DOUBLE PRECISION,
    "home_wp_post" DOUBLE PRECISION,
    "away_wp_post" DOUBLE PRECISION,
    "vegas_wp" DOUBLE PRECISION,
    "vegas_home_wp" DOUBLE PRECISION,
    "total_home_rush_wpa" DOUBLE PRECISION,
    "total_away_rush_wpa" DOUBLE PRECISION,
    "total_home_pass_wpa" DOUBLE PRECISION,
    "total_away_pass_wpa" DOUBLE PRECISION,
    "air_wpa" DOUBLE PRECISION,
    "yac_wpa" DOUBLE PRECISION,
    "comp_air_wpa" DOUBLE PRECISION,
    "comp_yac_wpa" DOUBLE PRECISION,
    "total_home_comp_air_wpa" DOUBLE PRECISION,
    "total_away_comp_air_wpa" DOUBLE PRECISION,
    "total_home_comp_yac_wpa" DOUBLE PRECISION,
    "total_away_comp_yac_wpa" DOUBLE PRECISION,
    "total_home_raw_air_wpa" DOUBLE PRECISION,
    "total_away_raw_air_wpa" DOUBLE PRECISION,
    "total_home_raw_yac_wpa" DOUBLE PRECISION,
    "total_away_raw_yac_wpa" DOUBLE PRECISION,
    "punt_blocked" DOUBLE PRECISION,
    "first_down_rush" DOUBLE PRECISION,
    "first_down_pass" DOUBLE PRECISION,
    "first_down_penalty" DOUBLE PRECISION,
    "third_down_converted" DOUBLE PRECISION,
    "third_down_failed" DOUBLE PRECISION,
    "fourth_down_converted" DOUBLE PRECISION,
    "fourth_down_failed" DOUBLE PRECISION,
    "incomplete_pass" DOUBLE PRECISION,
    "touchback" DOUBLE PRECISION,
    "interception" DOUBLE PRECISION,
    "punt_inside_twenty" DOUBLE PRECISION,
    "punt_in_endzone" DOUBLE PRECISION,
    "punt_out_of_bounds" DOUBLE PRECISION,
    "punt_downed" DOUBLE PRECISION,
    "punt_fair_catch" DOUBLE PRECISION,
    "kickoff_inside_twenty" DOUBLE PRECISION,
    "kickoff_in_endzone" DOUBLE PRECISION,
    "kickoff_out_of_bounds" DOUBLE PRECISION,
    "kickoff_downed" DOUBLE PRECISION,
    "kickoff_fair_catch" DOUBLE PRECISION,
    "fumble_forced" DOUBLE PRECISION,
    "fumble_not_forced" DOUBLE PRECISION,
    "fumble_out_of_bounds" DOUBLE PRECISION,
    "solo_tackle" DOUBLE PRECISION,
    "safety" DOUBLE PRECISION,
    "penalty" DOUBLE PRECISION,
    "tackled_for_loss" DOUBLE PRECISION,
    "fumble_lost" DOUBLE PRECISION,
    "own_kickoff_recovery" DOUBLE PRECISION,
    "own_kickoff_recovery_td" DOUBLE PRECISION,
    "qb_hit" DOUBLE PRECISION,
    "rush_attempt" DOUBLE PRECISION,
    "pass_attempt" DOUBLE PRECISION,
    "sack" DOUBLE PRECISION,
    "touchdown" DOUBLE PRECISION,
    "pass_touchdown" DOUBLE PRECISION,
    "rush_touchdown" DOUBLE PRECISION,
    "return_touchdown" DOUBLE PRECISION,
    "extra_point_attempt" DOUBLE PRECISION,
    "two_point_attempt" DOUBLE PRECISION,
    "field_goal_attempt" DOUBLE PRECISION,
    "kickoff_attempt" DOUBLE PRECISION,
    "punt_attempt" DOUBLE PRECISION,
    "fumble" DOUBLE PRECISION,
    "complete_pass" DOUBLE PRECISION,
    "assist_tackle" DOUBLE PRECISION,
    "lateral_reception" DOUBLE PRECISION,
    "lateral_rush" DOUBLE PRECISION,
    "lateral_return" DOUBLE PRECISION,
    "lateral_recovery" DOUBLE PRECISION,
    "passer_player_id" TEXT,
    "passer_player_name" TEXT,
    "passing_yards" DOUBLE PRECISION,
    "receiver_player_id" TEXT,
    "receiver_player_name" TEXT,
    "receiving_yards" DOUBLE PRECISION,
    "rusher_player_id" TEXT,
    "rusher_player_name" TEXT,
    "rushing_yards" DOUBLE PRECISION,
    "lateral_receiver_player_id" TEXT,
    "lateral_receiver_player_name" TEXT,
    "lateral_receiving_yards" DOUBLE PRECISION,
    "lateral_rusher_player_id" TEXT,
    "lateral_rusher_player_name" TEXT,
    "lateral_rushing_yards" DOUBLE PRECISION,
    "lateral_sack_player_id" TEXT,
    "lateral_sack_player_name" TEXT,
    "interception_player_id" TEXT,
    "interception_player_name" TEXT,
    "lateral_interception_player_id" TEXT,
    "lateral_interception_player_name" TEXT,
    "punt_returner_player_id" TEXT,
    "punt_returner_player_name" TEXT,
    "lateral_punt_returner_player_id" TEXT,
    "lateral_punt_returner_player_name" TEXT,
    "kickoff_returner_player_name" TEXT,
    "kickoff_returner_player_id" TEXT,
    "lateral_kickoff_returner_player_id" TEXT,
    "lateral_kickoff_returner_player_name" TEXT,
    "punter_player_id" TEXT,
    "punter_player_name" TEXT,
    "kicker_player_name" TEXT,
    "kicker_player_id" TEXT,
    "own_kickoff_recovery_player_id" TEXT,
    "own_kickoff_recovery_player_name" TEXT,
    "blocked_player_id" TEXT,
    "blocked_player_name" TEXT,
    "tackle_for_loss_1_player_id" TEXT,
    "tackle_for_loss_1_player_name" TEXT,
    "tackle_for_loss_2_player_id" TEXT,
    "tackle_for_loss_2_player_name" TEXT,
    "qb_hit_1_player_id" TEXT,
    "qb_hit_1_player_name" TEXT,
    "qb_hit_2_player_id" TEXT,
    "qb_hit_2_player_name" TEXT,
    "forced_fumble_player_1_team" TEXT,
    "forced_fumble_player_1_player_id" TEXT,
    "forced_fumble_player_1_player_name" TEXT,
    "forced_fumble_player_2_team" TEXT,
    "forced_fumble_player_2_player_id" TEXT,
    "forced_fumble_player_2_player_name" TEXT,
    "solo_tackle_1_team" TEXT,
    "solo_tackle_2_team" TEXT,
    "solo_tackle_1_player_id" TEXT,
    "solo_tackle_2_player_id" TEXT,
    "solo_tackle_1_player_name" TEXT,
    "solo_tackle_2_player_name" TEXT,
    "assist_tackle_1_player_id" TEXT,
    "assist_tackle_1_player_name" TEXT,
    "assist_tackle_1_team" TEXT,
    "assist_tackle_2_player_id" TEXT,
    "assist_tackle_2_player_name" TEXT,
    "assist_tackle_2_team" TEXT,
    "assist_tackle_3_player_id" TEXT,
    "assist_tackle_3_player_name" TEXT,
    "assist_tackle_3_team" TEXT,
    "assist_tackle_4_player_id" TEXT,
    "assist_tackle_4_player_name" TEXT,
    "assist_tackle_4_team" TEXT,
    "tackle_with_assist" DOUBLE PRECISION,
    "tackle_with_assist_1_player_id" TEXT,
    "tackle_with_assist_1_player_name" TEXT,
    "tackle_with_assist_1_team" TEXT,
    "tackle_with_assist_2_player_id" TEXT,
    "tackle_with_assist_2_player_name" TEXT,
    "tackle_with_assist_2_team" TEXT,
    "pass_defense_1_player_id" TEXT,
    "pass_defense_1_player_name" TEXT,
    "pass_defense_2_player_id" TEXT,
    "pass_defense_2_player_name" TEXT,
    "fumbled_1_team" TEXT,
    "fumbled_1_player_id" TEXT,
    "fumbled_1_player_name" TEXT,
    "fumbled_2_player_id" TEXT,
    "fumbled_2_player_name" TEXT,
    "fumbled_2_team" TEXT,
    "fumble_recovery_1_team" TEXT,
    "fumble_recovery_1_yards" DOUBLE PRECISION,
    "fumble_recovery_1_player_id" TEXT,
    "fumble_recovery_1_player_name" TEXT,
    "fumble_recovery_2_team" TEXT,
    "fumble_recovery_2_yards" DOUBLE PRECISION,
    "fumble_recovery_2_player_id" TEXT,
    "fumble_recovery_2_player_name" TEXT,
    "sack_player_id" TEXT,
    "sack_player_name" TEXT,
    "half_sack_1_player_id" TEXT,
    "half_sack_1_player_name" TEXT,
    "half_sack_2_player_id" TEXT,
    "half_sack_2_player_name" TEXT,
    "return_team" TEXT,
    "return_yards" DOUBLE PRECISION,
    "penalty_team" TEXT,
    "penalty_player_id" TEXT,
    "penalty_player_name" TEXT,
    "penalty_yards" DOUBLE PRECISION,
    "replay_or_challenge" DOUBLE PRECISION,
    "replay_or_challenge_result" TEXT,
    "penalty_type" TEXT,
    "defensive_two_point_attempt" DOUBLE PRECISION,
    "defensive_two_point_conv" DOUBLE PRECISION,
    "defensive_extra_point_attempt" DOUBLE PRECISION,
    "defensive_extra_point_conv" DOUBLE PRECISION,
    "safety_player_name" TEXT,
    "safety_player_id" TEXT,
    "season" BIGINT,
    "cp" DOUBLE PRECISION,
    "cpoe" DOUBLE PRECISION,
    "series" DOUBLE PRECISION,
    "series_success" DOUBLE PRECISION,
    "series_result" TEXT,
    "order_sequence" DOUBLE PRECISION,
    "start_time" TEXT,
    "time_of_day" TEXT,
    "stadium" TEXT,
    "weather" TEXT,
    "nfl_api_id" TEXT,
    "play_clock" TEXT,
    "play_deleted" DOUBLE PRECISION,
    "play_type_nfl" TEXT,
    "special_teams_play" DOUBLE PRECISION,
    "st_play_type" TEXT,
    "end_clock_time" TEXT,
    "end_yard_line" TEXT,
    "fixed_drive" DOUBLE PRECISION,
    "fixed_drive_result" TEXT,
    "drive_real_start_time" TEXT,
    "drive_play_count" DOUBLE PRECISION,
    "drive_time_of_possession" TEXT,
    "drive_first_downs" DOUBLE PRECISION,
    "drive_inside20" DOUBLE PRECISION,
    "drive_ended_with_score" DOUBLE PRECISION,
    "drive_quarter_start" DOUBLE PRECISION,
    "drive_quarter_end" DOUBLE PRECISION,
    "drive_yards_penalized" DOUBLE PRECISION,
    "drive_start_transition" TEXT,
    "drive_end_transition" TEXT,
    "drive_game_clock_start" TEXT,
    "drive_game_clock_end" TEXT,
    "drive_start_yard_line" TEXT,
    "drive_end_yard_line" TEXT,
    "drive_play_id_started" DOUBLE PRECISION,
    "drive_play_id_ended" DOUBLE PRECISION,
    "away_score" BIGINT,
    "home_score" BIGINT,
    "location" TEXT,
    "result" BIGINT,
    "total" BIGINT,
    "spread_line" DOUBLE PRECISION,
    "total_line" DOUBLE PRECISION,
    "div_game" BIGINT,
    "roof" TEXT,
    "surface" TEXT,
    "temp" BIGINT,
    "wind" BIGINT,
    "home_coach" TEXT,
    "away_coach" TEXT,
    "stadium_id" TEXT,
    "game_stadium" TEXT,
    "aborted_play" DOUBLE PRECISION,
    "success" DOUBLE PRECISION,
    "passer" TEXT,
    "passer_jersey_number" BIGINT,
    "rusher" TEXT,
    "rusher_jersey_number" BIGINT,
    "receiver" TEXT,
    "receiver_jersey_number" BIGINT,
    "pass" DOUBLE PRECISION,
    "rush" DOUBLE PRECISION,
    "first_down" DOUBLE PRECISION,
    "special" DOUBLE PRECISION,
    "play" DOUBLE PRECISION,
    "passer_id" TEXT,
    "rusher_id" TEXT,
    "receiver_id" TEXT,
    "name" TEXT,
    "jersey_number" BIGINT,
    "id" TEXT,
    "fantasy_player_name" TEXT,
    "fantasy_player_id" TEXT,
    "fantasy" TEXT,
    "fantasy_id" TEXT,
    "out_of_bounds" DOUBLE PRECISION,
    "home_opening_kickoff" DOUBLE PRECISION,
    "qb_epa" DOUBLE PRECISION,
    "xyac_epa" DOUBLE PRECISION,
    "xyac_mean_yardage" DOUBLE PRECISION,
    "xyac_median_yardage" BIGINT,
    "xyac_success" DOUBLE PRECISION,
    "xyac_fd" DOUBLE PRECISION,
    "xpass" DOUBLE PRECISION,
    "pass_oe" DOUBLE PRECISION,

    CONSTRAINT "pbp_pkey" PRIMARY KEY ("game_id","play_id")
);

-- CreateTable
CREATE TABLE "player_stats" (
    "player_id" TEXT,
    "player_name" TEXT,
    "player_display_name" TEXT,
    "position" TEXT,
    "position_group" TEXT,
    "headshot_url" TEXT,
    "season" BIGINT,
    "week" BIGINT,
    "season_type" TEXT,
    "team" TEXT,
    "opponent_team" TEXT,
    "completions" BIGINT,
    "attempts" BIGINT,
    "passing_yards" BIGINT,
    "passing_tds" BIGINT,
    "passing_interceptions" BIGINT,
    "sacks_suffered" BIGINT,
    "sack_yards_lost" BIGINT,
    "sack_fumbles" BIGINT,
    "sack_fumbles_lost" BIGINT,
    "passing_air_yards" BIGINT,
    "passing_yards_after_catch" BIGINT,
    "passing_first_downs" BIGINT,
    "passing_epa" DOUBLE PRECISION,
    "passing_cpoe" DOUBLE PRECISION,
    "passing_2pt_conversions" BIGINT,
    "pacr" DOUBLE PRECISION,
    "carries" BIGINT,
    "rushing_yards" BIGINT,
    "rushing_tds" BIGINT,
    "rushing_fumbles" BIGINT,
    "rushing_fumbles_lost" BIGINT,
    "rushing_first_downs" BIGINT,
    "rushing_epa" DOUBLE PRECISION,
    "rushing_2pt_conversions" BIGINT,
    "receptions" BIGINT,
    "targets" BIGINT,
    "receiving_yards" BIGINT,
    "receiving_tds" BIGINT,
    "receiving_fumbles" BIGINT,
    "receiving_fumbles_lost" BIGINT,
    "receiving_air_yards" BIGINT,
    "receiving_yards_after_catch" BIGINT,
    "receiving_first_downs" BIGINT,
    "receiving_epa" DOUBLE PRECISION,
    "receiving_2pt_conversions" BIGINT,
    "racr" DOUBLE PRECISION,
    "target_share" DOUBLE PRECISION,
    "air_yards_share" DOUBLE PRECISION,
    "wopr" DOUBLE PRECISION,
    "special_teams_tds" BIGINT,
    "def_tackles_solo" BIGINT,
    "def_tackles_with_assist" BIGINT,
    "def_tackle_assists" BIGINT,
    "def_tackles_for_loss" BIGINT,
    "def_tackles_for_loss_yards" BIGINT,
    "def_fumbles_forced" BIGINT,
    "def_sacks" DOUBLE PRECISION,
    "def_sack_yards" DOUBLE PRECISION,
    "def_qb_hits" BIGINT,
    "def_interceptions" BIGINT,
    "def_interception_yards" BIGINT,
    "def_pass_defended" BIGINT,
    "def_tds" BIGINT,
    "def_fumbles" BIGINT,
    "def_safeties" BIGINT,
    "misc_yards" BIGINT,
    "fumble_recovery_own" BIGINT,
    "fumble_recovery_yards_own" BIGINT,
    "fumble_recovery_opp" BIGINT,
    "fumble_recovery_yards_opp" BIGINT,
    "fumble_recovery_tds" BIGINT,
    "penalties" BIGINT,
    "penalty_yards" BIGINT,
    "punt_returns" BIGINT,
    "punt_return_yards" BIGINT,
    "kickoff_returns" BIGINT,
    "kickoff_return_yards" BIGINT,
    "fg_made" BIGINT,
    "fg_att" BIGINT,
    "fg_missed" BIGINT,
    "fg_blocked" BIGINT,
    "fg_long" BIGINT,
    "fg_pct" DOUBLE PRECISION,
    "fg_made_0_19" BIGINT,
    "fg_made_20_29" BIGINT,
    "fg_made_30_39" BIGINT,
    "fg_made_40_49" BIGINT,
    "fg_made_50_59" BIGINT,
    "fg_made_60_" BIGINT,
    "fg_missed_0_19" BIGINT,
    "fg_missed_20_29" BIGINT,
    "fg_missed_30_39" BIGINT,
    "fg_missed_40_49" BIGINT,
    "fg_missed_50_59" BIGINT,
    "fg_missed_60_" BIGINT,
    "fg_made_list" TEXT,
    "fg_missed_list" TEXT,
    "fg_blocked_list" TEXT,
    "fg_made_distance" BIGINT,
    "fg_missed_distance" BIGINT,
    "fg_blocked_distance" BIGINT,
    "pat_made" BIGINT,
    "pat_att" BIGINT,
    "pat_missed" BIGINT,
    "pat_blocked" BIGINT,
    "pat_pct" DOUBLE PRECISION,
    "gwfg_made" BIGINT,
    "gwfg_att" BIGINT,
    "gwfg_missed" BIGINT,
    "gwfg_blocked" BIGINT,
    "gwfg_distance" BIGINT,
    "fantasy_points" DOUBLE PRECISION,
    "fantasy_points_ppr" DOUBLE PRECISION,
    "id" SERIAL NOT NULL,

    CONSTRAINT "player_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "players" (
    "gsis_id" TEXT,
    "display_name" TEXT,
    "common_first_name" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "short_name" TEXT,
    "football_name" TEXT,
    "suffix" TEXT,
    "esb_id" TEXT,
    "nfl_id" TEXT,
    "pfr_id" TEXT,
    "pff_id" TEXT,
    "otc_id" TEXT,
    "espn_id" TEXT,
    "smart_id" TEXT,
    "birth_date" TEXT,
    "position_group" TEXT,
    "position" TEXT,
    "ngs_position_group" TEXT,
    "ngs_position" TEXT,
    "height" BIGINT,
    "weight" BIGINT,
    "headshot" TEXT,
    "college_name" TEXT,
    "college_conference" TEXT,
    "jersey_number" TEXT,
    "rookie_season" BIGINT,
    "last_season" BIGINT,
    "latest_team" TEXT,
    "status" TEXT,
    "ngs_status" TEXT,
    "ngs_status_short_description" TEXT,
    "years_of_experience" BIGINT,
    "pff_position" TEXT,
    "pff_status" TEXT,
    "draft_year" BIGINT,
    "draft_round" BIGINT,
    "draft_pick" BIGINT,
    "draft_team" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "players_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rosters" (
    "season" BIGINT,
    "team" TEXT,
    "position" TEXT,
    "depth_chart_position" TEXT,
    "jersey_number" TEXT,
    "status" TEXT,
    "full_name" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "birth_date" DATE,
    "height" BIGINT,
    "weight" BIGINT,
    "college" TEXT,
    "gsis_id" TEXT,
    "espn_id" TEXT,
    "sportradar_id" TEXT,
    "yahoo_id" TEXT,
    "rotowire_id" TEXT,
    "pff_id" TEXT,
    "pfr_id" TEXT,
    "fantasy_data_id" TEXT,
    "sleeper_id" TEXT,
    "years_exp" BIGINT,
    "headshot_url" TEXT,
    "ngs_position" TEXT,
    "week" BIGINT,
    "game_type" TEXT,
    "status_description_abbr" TEXT,
    "football_name" TEXT,
    "esb_id" TEXT,
    "gsis_it_id" TEXT,
    "smart_id" TEXT,
    "entry_year" BIGINT,
    "rookie_year" BIGINT,
    "draft_club" TEXT,
    "draft_number" BIGINT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "rosters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rosters_weekly" (
    "season" BIGINT,
    "team" TEXT,
    "position" TEXT,
    "depth_chart_position" TEXT,
    "jersey_number" TEXT,
    "status" TEXT,
    "full_name" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "birth_date" DATE,
    "height" BIGINT,
    "weight" BIGINT,
    "college" TEXT,
    "gsis_id" TEXT,
    "espn_id" TEXT,
    "sportradar_id" TEXT,
    "yahoo_id" TEXT,
    "rotowire_id" TEXT,
    "pff_id" TEXT,
    "pfr_id" TEXT,
    "fantasy_data_id" TEXT,
    "sleeper_id" TEXT,
    "years_exp" BIGINT,
    "headshot_url" TEXT,
    "ngs_position" TEXT,
    "week" BIGINT,
    "game_type" TEXT,
    "status_description_abbr" TEXT,
    "football_name" TEXT,
    "esb_id" TEXT,
    "gsis_it_id" TEXT,
    "smart_id" TEXT,
    "entry_year" BIGINT,
    "rookie_year" BIGINT,
    "draft_club" TEXT,
    "draft_number" BIGINT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "rosters_weekly_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "schedules" (
    "game_id" TEXT,
    "season" BIGINT,
    "game_type" TEXT,
    "week" BIGINT,
    "gameday" TEXT,
    "weekday" TEXT,
    "gametime" TEXT,
    "away_team" TEXT,
    "away_score" BIGINT,
    "home_team" TEXT,
    "home_score" BIGINT,
    "location" TEXT,
    "result" BIGINT,
    "total" BIGINT,
    "overtime" BIGINT,
    "old_game_id" TEXT,
    "gsis" BIGINT,
    "nfl_detail_id" TEXT,
    "pfr" TEXT,
    "pff" BIGINT,
    "espn" TEXT,
    "ftn" BIGINT,
    "away_rest" BIGINT,
    "home_rest" BIGINT,
    "away_moneyline" BIGINT,
    "home_moneyline" BIGINT,
    "spread_line" DOUBLE PRECISION,
    "away_spread_odds" BIGINT,
    "home_spread_odds" BIGINT,
    "total_line" DOUBLE PRECISION,
    "under_odds" BIGINT,
    "over_odds" BIGINT,
    "div_game" BIGINT,
    "roof" TEXT,
    "surface" TEXT,
    "temp" BIGINT,
    "wind" BIGINT,
    "away_qb_id" TEXT,
    "home_qb_id" TEXT,
    "away_qb_name" TEXT,
    "home_qb_name" TEXT,
    "away_coach" TEXT,
    "home_coach" TEXT,
    "referee" TEXT,
    "stadium_id" TEXT,
    "stadium" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "snap_counts" (
    "game_id" TEXT,
    "pfr_game_id" TEXT,
    "season" BIGINT,
    "game_type" TEXT,
    "week" BIGINT,
    "player" TEXT,
    "pfr_player_id" TEXT,
    "position" TEXT,
    "team" TEXT,
    "opponent" TEXT,
    "offense_snaps" DOUBLE PRECISION,
    "offense_pct" DOUBLE PRECISION,
    "defense_snaps" DOUBLE PRECISION,
    "defense_pct" DOUBLE PRECISION,
    "st_snaps" DOUBLE PRECISION,
    "st_pct" DOUBLE PRECISION,
    "id" SERIAL NOT NULL,

    CONSTRAINT "snap_counts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "team_stats" (
    "season" BIGINT,
    "week" BIGINT,
    "team" TEXT,
    "season_type" TEXT,
    "opponent_team" TEXT,
    "completions" BIGINT,
    "attempts" BIGINT,
    "passing_yards" BIGINT,
    "passing_tds" BIGINT,
    "passing_interceptions" BIGINT,
    "sacks_suffered" BIGINT,
    "sack_yards_lost" BIGINT,
    "sack_fumbles" BIGINT,
    "sack_fumbles_lost" BIGINT,
    "passing_air_yards" BIGINT,
    "passing_yards_after_catch" BIGINT,
    "passing_first_downs" BIGINT,
    "passing_epa" DOUBLE PRECISION,
    "passing_cpoe" DOUBLE PRECISION,
    "passing_2pt_conversions" BIGINT,
    "carries" BIGINT,
    "rushing_yards" BIGINT,
    "rushing_tds" BIGINT,
    "rushing_fumbles" BIGINT,
    "rushing_fumbles_lost" BIGINT,
    "rushing_first_downs" BIGINT,
    "rushing_epa" DOUBLE PRECISION,
    "rushing_2pt_conversions" BIGINT,
    "receptions" BIGINT,
    "targets" BIGINT,
    "receiving_yards" BIGINT,
    "receiving_tds" BIGINT,
    "receiving_fumbles" BIGINT,
    "receiving_fumbles_lost" BIGINT,
    "receiving_air_yards" BIGINT,
    "receiving_yards_after_catch" BIGINT,
    "receiving_first_downs" BIGINT,
    "receiving_epa" DOUBLE PRECISION,
    "receiving_2pt_conversions" BIGINT,
    "special_teams_tds" BIGINT,
    "def_tackles_solo" BIGINT,
    "def_tackles_with_assist" BIGINT,
    "def_tackle_assists" BIGINT,
    "def_tackles_for_loss" BIGINT,
    "def_tackles_for_loss_yards" BIGINT,
    "def_fumbles_forced" BIGINT,
    "def_sacks" DOUBLE PRECISION,
    "def_sack_yards" DOUBLE PRECISION,
    "def_qb_hits" BIGINT,
    "def_interceptions" BIGINT,
    "def_interception_yards" BIGINT,
    "def_pass_defended" BIGINT,
    "def_tds" BIGINT,
    "def_fumbles" BIGINT,
    "def_safeties" BIGINT,
    "misc_yards" BIGINT,
    "fumble_recovery_own" BIGINT,
    "fumble_recovery_yards_own" BIGINT,
    "fumble_recovery_opp" BIGINT,
    "fumble_recovery_yards_opp" BIGINT,
    "fumble_recovery_tds" BIGINT,
    "penalties" BIGINT,
    "penalty_yards" BIGINT,
    "timeouts" BIGINT,
    "punt_returns" BIGINT,
    "punt_return_yards" BIGINT,
    "kickoff_returns" BIGINT,
    "kickoff_return_yards" BIGINT,
    "fg_made" BIGINT,
    "fg_att" BIGINT,
    "fg_missed" BIGINT,
    "fg_blocked" BIGINT,
    "fg_long" BIGINT,
    "fg_pct" DOUBLE PRECISION,
    "fg_made_0_19" BIGINT,
    "fg_made_20_29" BIGINT,
    "fg_made_30_39" BIGINT,
    "fg_made_40_49" BIGINT,
    "fg_made_50_59" BIGINT,
    "fg_made_60_" BIGINT,
    "fg_missed_0_19" BIGINT,
    "fg_missed_20_29" BIGINT,
    "fg_missed_30_39" BIGINT,
    "fg_missed_40_49" BIGINT,
    "fg_missed_50_59" BIGINT,
    "fg_missed_60_" BIGINT,
    "fg_made_list" TEXT,
    "fg_missed_list" TEXT,
    "fg_blocked_list" TEXT,
    "fg_made_distance" BIGINT,
    "fg_missed_distance" BIGINT,
    "fg_blocked_distance" BIGINT,
    "pat_made" BIGINT,
    "pat_att" BIGINT,
    "pat_missed" BIGINT,
    "pat_blocked" BIGINT,
    "pat_pct" DOUBLE PRECISION,
    "gwfg_made" BIGINT,
    "gwfg_att" BIGINT,
    "gwfg_missed" BIGINT,
    "gwfg_blocked" BIGINT,
    "gwfg_distance" BIGINT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "team_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teams" (
    "team_abbr" TEXT,
    "team_name" TEXT,
    "team_id" BIGINT,
    "team_nick" TEXT,
    "team_conf" TEXT,
    "team_division" TEXT,
    "team_color" TEXT,
    "team_color2" TEXT,
    "team_color3" TEXT,
    "team_color4" TEXT,
    "team_logo_wikipedia" TEXT,
    "team_logo_espn" TEXT,
    "team_wordmark" TEXT,
    "team_conference_logo" TEXT,
    "team_league_logo" TEXT,
    "team_logo_squared" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trades" (
    "trade_id" DOUBLE PRECISION,
    "season" BIGINT,
    "trade_date" DATE,
    "gave" TEXT,
    "received" TEXT,
    "pick_season" DOUBLE PRECISION,
    "pick_round" DOUBLE PRECISION,
    "pick_number" DOUBLE PRECISION,
    "conditional" DOUBLE PRECISION,
    "pfr_id" TEXT,
    "pfr_name" TEXT,
    "id" SERIAL NOT NULL,

    CONSTRAINT "trades_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "combine_unique" ON "combine"("pfr_id");

-- CreateIndex
CREATE UNIQUE INDEX "depth_charts_unique" ON "depth_charts"("gsis_id", "season", "week", "elias_id");

-- CreateIndex
CREATE UNIQUE INDEX "draft_picks_unique" ON "draft_picks"("season", "round", "pick", "pfr_player_id");

-- CreateIndex
CREATE UNIQUE INDEX "ff_opportunity_unique" ON "ff_opportunity"("game_id", "player_id");

-- CreateIndex
CREATE UNIQUE INDEX "ff_playerids_unique" ON "ff_playerids"("mfl_id", "sportradar_id", "fantasypros_id", "gsis_id", "pff_id", "sleeper_id", "nfl_id", "pfr_id");

-- CreateIndex
CREATE UNIQUE INDEX "ff_rankings_unique" ON "ff_rankings"("id", "sportsdata_id", "yahoo_id", "cbs_id");

-- CreateIndex
CREATE UNIQUE INDEX "ftn_charting_unique" ON "ftn_charting"("nflverse_game_id", "nflverse_play_id");

-- CreateIndex
CREATE UNIQUE INDEX "nextgen_stats_unique" ON "nextgen_stats"("season", "week", "player_gsis_id");

-- CreateIndex
CREATE UNIQUE INDEX "officials_unique" ON "officials"("game_id", "official_id");

-- CreateIndex
CREATE UNIQUE INDEX "participation_unique" ON "participation"("nflverse_game_id", "play_id");

-- CreateIndex
CREATE UNIQUE INDEX "pbp_unique" ON "pbp"("game_id", "play_id");

-- CreateIndex
CREATE UNIQUE INDEX "player_stats_unique" ON "player_stats"("player_id", "season", "week");

-- CreateIndex
CREATE INDEX "players_display_name_idx" ON "players"("display_name");

-- CreateIndex
CREATE UNIQUE INDEX "players_unique" ON "players"("gsis_id", "esb_id", "nfl_id", "pfr_id", "pff_id", "otc_id", "espn_id", "smart_id");

-- CreateIndex
CREATE UNIQUE INDEX "rosters_unique" ON "rosters"("season", "team", "gsis_id", "espn_id", "sportradar_id", "yahoo_id", "rotowire_id", "pff_id", "pfr_id", "fantasy_data_id", "sleeper_id");

-- CreateIndex
CREATE UNIQUE INDEX "rosters_weekly_unique" ON "rosters_weekly"("season", "team", "gsis_id", "espn_id", "sportradar_id", "yahoo_id", "rotowire_id", "pff_id", "pfr_id", "fantasy_data_id", "sleeper_id", "week");

-- CreateIndex
CREATE UNIQUE INDEX "schedules_unique" ON "schedules"("game_id", "season", "week");

-- CreateIndex
CREATE UNIQUE INDEX "snap_counts_unique" ON "snap_counts"("game_id", "pfr_game_id", "pfr_player_id", "season", "week");

-- CreateIndex
CREATE UNIQUE INDEX "team_stats_unique" ON "team_stats"("season", "week");

-- CreateIndex
CREATE UNIQUE INDEX "teams_unique" ON "teams"("team_id");

-- CreateIndex
CREATE UNIQUE INDEX "trades_unique" ON "trades"("trade_id", "pfr_id");

-- CreateIndex
CREATE UNIQUE INDEX "contracts_unique" ON "contracts"("otc_id", "gsis_id");
